# fly.toml app configuration file generated for justbazar on 2024-12-24T21:49:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'justbazar'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "auction_data"
  destination = "/data"

[[vm]]
  size = 'shared-cpu-1x'
